server:
  port: 8082

spring:
  application:
    name: client-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-client
            client-secret: demo-secret
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
